<a href="https://colab.research.google.com/github/ragumass55/Data-Analysis-Dashboard/blob/main/super_store_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

df = pd.read_csv("/super store 3.csv", encoding='latin1')

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,2016,11
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,2016,11
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,2016,6
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,2015,10
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,2015,10

In [ ]:
df.shape

(9994, 23)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Order Year     9994 non-null   int64
 22  Order Month    9994 non-null   int64
dtypes: float64(3), int64(5), object(15)
memory usage: 1.8+ MB

In [ ]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Order Year       0
Order Month      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[['Sales','Profit','Quantity','Discount']].describe()

              Sales       Profit     Quantity     Discount
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858022    28.656973     3.789574     0.156203
std      623.245131   234.260203     2.225110     0.206452
min        0.440000 -6599.980000     1.000000     0.000000
25%       17.280000     1.730000     2.000000     0.000000
50%       54.490000     8.665000     3.000000     0.200000
75%      209.940000    29.360000     5.000000     0.200000
max    22638.480000  8399.980000    14.000000     0.800000

In [ ]:
df.groupby('Order Year')['Sales'].sum().sum() == df['Sales'].sum()

np.True_

In [ ]:
(df['Sales'].sum())

np.float64(2297201.07)

In [ ]:
(df['Sales']>0).sum()

np.int64(9994)

In [ ]:
(df['Sales'] < 0).sum()

np.int64(0)

In [ ]:
(df['Quantity'] <= 0).sum()

np.int64(0)

In [ ]:
df['Sales'].sum()

np.float64(2297201.07)

In [ ]:
df['Profit'].sum()

np.float64(286397.79000000004)

In [ ]:
df['Quantity'].sum()

np.int64(37873)

In [ ]:
df[(df['Discount'] < 0) | (df['Discount'] > 1)].shape[0]

0

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
(df['Profit'].sum()*100)/df['Sales'].sum()

np.float64(12.467249547293658)